apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  annotations:
    sonarqube.org/project-key: com.healthedge.connector:connector-versions
spec:
  type: library
  owner: guest
  lifecycle: experimental
